# Generated by Django 4.2.3 on 2023-07-13 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teclados',
            new_name='Teclado',
        ),
    ]
