# Generated by Django 4.2.2 on 2023-07-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_teclado_autor_teclado_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teclado',
            name='autor',
            field=models.CharField(default='', max_length=20),
        ),
    ]
