# Generated by Django 4.2.2 on 2023-07-18 16:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_teclado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teclado',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
