# Generated by Django 4.2.2 on 2023-07-18 22:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_infoextra_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoextra',
            name='link',
        ),
        migrations.AddField(
            model_name='infoextra',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
